name: niva
description: Hair and Beauty App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.1


  lecle_flutter_carousel_pro: ^0.0.1
 

  dots_indicator: ^2.0.0

  get: ^4.1.4

  cloud_firestore: ^4.8.0

  firebase_auth: ^4.6.2

  firebase_storage: ^11.2.2

  image_picker: ^0.8.7+5

  firebase_core: ^2.13.1

  cupertino_icons: ^1.0.2


#  auto_size_text: ^3.0.0
#  built_collection: ^5.2.0
#  built_value: ^8.1.0
#  cached_network_image: ^3.2.0
 # chewie: ^1.4.0
 
#  flutter_animate: ^1.0.0
#  flutter_cache_manager: ^4.2.0
#  flutter_spinkit: ^6.2.0
 
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
#  intl: ^0.17.0
#  json_path: ^0.5.3
#  json_serializable: ^6.3.0
# page_transition: ^2.0.8
#  provider: ^6.2.0
 #rxdart: ^0.27.3
  
 # sign_in_with_apple: ^3.0.0
 # simple_gradient_text: ^1.2.3
 #smooth_page_indicator: ^1.1.0
  

#  url_launcher: ^6.0.10
#  video_player: ^2.2.5
  google_maps_flutter: ^2.2.8
  timeago: ^3.4.0



  #circle_bottom_navigation_bar: ^1.0.0 to be implemented in future, I like the animation
  custom_navigation_bar: ^0.8.2




dev_dependencies:
  flutter_test:
    sdk: flutter


  
  


flutter:


  uses-material-design: true

  assets:
   - assets/image/brush1.jpg
   - assets/image/brush2.jpg
   - assets/image/laroche1.jpg
   - assets/image/laroche2.jpg
   - assets/image/laroche3.jpg
   - assets/image/lipstick1.jpg
   - assets/image/lipstick2.jpg
   - assets/image/locs.jpg
   - assets/image/locs1.jpg
   - assets/image/locs3.jpg
   - assets/image/locs4.jpg
   - assets/image/makeup1.jpg
   - assets/image/makeup2.jpg
   - assets/image/makeup3.jpg
   - assets/image/makeup4.jpg
   - assets/image/nail1.jpg
   - assets/image/nail2.jpg
   - assets/image/nail3.jpg
   - assets/image/nail4.jpg
   - assets/image/splash1.png
   - assets/image/splash2.png
   - assets/image/splash3.png

